name: klondike
description: A follow-along with the Flame Game Engine Klondike tutorial.
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.18.6
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0

flutter:
  assets:
    - assets/images/
